# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognize.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecognize.proto\"6\n\x11RecognizerControl\x12!\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x11.RecognizerAction\"\"\n\x10RecognizerResult\x12\x0e\n\x06result\x18\x01 \x01(\t*\'\n\x10RecognizerAction\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x32G\n\x11RecognizerService\x12\x32\n\tRecognize\x12\x12.RecognizerControl\x1a\x11.RecognizerResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognize_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOGNIZERACTION._serialized_start=111
  _RECOGNIZERACTION._serialized_end=150
  _RECOGNIZERCONTROL._serialized_start=19
  _RECOGNIZERCONTROL._serialized_end=73
  _RECOGNIZERRESULT._serialized_start=75
  _RECOGNIZERRESULT._serialized_end=109
  _RECOGNIZERSERVICE._serialized_start=152
  _RECOGNIZERSERVICE._serialized_end=223
# @@protoc_insertion_point(module_scope)
